// HT-8: "Where you should feel it" (plan 2.4 item 5, 2.5). Inserts golden B's pre-rendered section string once
// (feel-<chromeId>.ts, generated by tools/plates/gen/feel.mjs) and binds golden B's behaviour (useFeelMap).
// Mount (plan 2.5): after two animation frames or when the section comes within one viewport, whichever is later;
// the chunk loads then, so the map is in before it is seen and golden B's timing starts from its own observer.
import { useEffect, useMemo, useRef, useState } from 'preact/hooks';
import type { SectionProps } from './index';
import { howToLoadFailed } from '../lazy';
import { useFeelMap } from '../feel/useFeelMap';
import { chromeIdOf } from '../PlateView';
import '../css/feel.css';

export interface FeelChunk { readonly default: { readonly id: string; readonly pre: string; readonly section: string } }
const CHUNKS = import.meta.glob<FeelChunk>('../../../howto/generated/feel-*.ts');
/** The chunk for a How-to: feel-<chromeId> (golden B's card id prefix, e.g. lateral-raise; supervisor ruling, #119). */
export const feelPath = (chromeId: string) => `../../../howto/generated/feel-${chromeId}.ts`;

/** Resolves once two frames have passed and `el` is within one viewport of the visible area. */
export function whenNear(el: Element, done: () => void): () => void {
  let frames = false, near = false, fired = false, raf = 0;
  const go = () => { if (frames && near && !fired) { fired = true; io?.disconnect(); done(); } };
  raf = requestAnimationFrame(() => { raf = requestAnimationFrame(() => { frames = true; go(); }); });
  const io = typeof IntersectionObserver === 'function'
    ? new IntersectionObserver(es => { if (es.some(e => e.isIntersecting)) { near = true; go(); } }, { rootMargin: '100% 0px' })
    : null;
  if (io) io.observe(el); else near = true;
  return () => { cancelAnimationFrame(raf); io?.disconnect(); };
}

export function Feel({ howTo }: SectionProps) {
  const host = useRef<HTMLDivElement>(null);
  const [section, setSection] = useState<string | null>(null);
  useEffect(() => {
    const load = CHUNKS[feelPath(chromeIdOf(howTo))];
    if (!load || !host.current) return;
    let live = true;
    const stop = whenNear(host.current, () => {
      void load().then(m => { if (live) setSection(m.default.section); }).catch(() => { if (live) howToLoadFailed(() => {}); });
    });
    return () => { live = false; stop(); };
  }, []);
  // inserted once (memoised; Preact never re-sets it), like the plate strings
  const inner = useMemo(() => (section ? { __html: section } : undefined), [section]);
  useFeelMap(host, section != null);
  return <div class="ht-feel-host" ref={host} dangerouslySetInnerHTML={inner} />;
}
